### PR TITLE
Extends the discount level on renewal

### LINKED ISSUE #100: Sponsored code expiration date not updated after renewal
The sponsor code of an actual sponsor who renew its membership (with sponsored seats) is reused by the system but its expiration date isn't updated, so the sponsored members can't renew their account, it says the sponsor code is expired.

plugin version:  0.10
pmpro version:  2.5.9.1

### LINKED ISSUE #111: Discount Codes for child accounts not renewing when parent membership renews.
**Describe the bug**
Child discount codes will always expire, and not renew upon parent account renewal. 

Code reference: https://github.com/strangerstudios/pmpro-sponsored-members/blob/dev/pmpro-sponsored-members.php#L243 (Removing this to let the code never expire should be okay)

**To Reproduce**
1. Signup for a parent account.
2. Set the expiration date of the code to a past date (to "spoof" the 1 year period)
3. Try checkout with the code. (Parent account/membership still active and valid)

**Expected behavior**
Proposed change is to set the discount code to never expire when created at parent checkout, as there are checks on registration that the parent account is active.

Code reference: https://github.com/strangerstudios/pmpro-sponsored-members/blob/dev/pmpro-sponsored-members.php#L713-L747

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by JarrydLong**
Extends the discount code expiration date and uses when the main level is renewed. 

Resolves #100
Resolves #111

Steps to test:

1. Sign up for the main level and ensure that a discount code is created
2. Sign up for the same level. The discount code expiration date and uses should be pushed forward. 
3. This will only happen when the main level is a recurring level. Once off levels don't have any effect on this.

### CODE REVIEW

File: pmpro-sponsored-members.php [hunk 1]
```diff
@@ -327,9 +328,43 @@ function pmprosm_sponsored_account_change( $level_id, $user_id ) {
...
+				$expiration = $discount_code->expires;
+				//We're extending the uses instead of resetting this
+				//Will need to test this a bit more for real-world use cases
+				$uses = $discount_code->uses;
+
+				$new_expiration_date = date('Y-m-d', strtotime( $expires . ' + '.$level->cycle_number.' '.$level->cycle_period ) );
+
+				$updated = $wpdb->update( $wpdb->pmpro_discount_codes, 
+					array (
+						'uses' => esc_sql( $uses + $seats ),
```
Comment (dparker1005) [inline pmpro-sponsored-members.php:355]: Do sites want to increase the amount of child seats that a parent has when the parent renews? I would imagine that many sites would want to keep the number of seats the same, similar to if they were using automatically recurring payments and the parent was just renewing their membership.
