### PR TITLE
Better handling of plurals on confirmation page

### LINKED ISSUE #95: "This code has 1 uses"
**Describe the bug**
In the `pmprosm_pmpro_confirmation_message()` function, if the code created only has one use, the message will show "This code has 1 uses". This should instead read "This code has 1 use".

https://github.com/strangerstudios/pmpro-sponsored-members/blob/c03ace06530fa0c948fd4257b249e6ecb9ae5f76/pmpro-sponsored-members.php#L650

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

### PR DESCRIPTION
**Pull request by JarrydLong**
### All Submissions:

* [x] Have you followed the [Contributing guideline](CONTRIBUTING.MD)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Better handling of the word 'uses' when a discount code only has 1 'use'

Resolves #95

### How to test the changes in this Pull Request:

1. Set discount code uses to only 1
2. Purchase a Sponsored Members level
3. The code displayed on the Confirmation page will show as 'This code has 1 use.' instead of 'This code has 1 uses'.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Better handling of plurals in some language on the confirmation page

### CODE REVIEW

File: pmpro-sponsored-members.php [hunk 1]
```diff
@@ -647,7 +647,7 @@ function pmprosm_pmpro_confirmation_message( $message ) {
 			if ( empty( $code->uses ) ) {
 				$message .= __( "This code has unlimited uses.", "pmpro-sponsored-members" );
 			} else {
-				$message .= sprintf( __( "This code has %d uses.", "pmpro-sponsored-members" ), $code->uses );
+				$message .= sprintf( ngettext( __( "This code has %d use.", "pmpro-sponsored-members" ), __( "This code has %d uses.", "pmpro-sponsored-members" ), $code->uses ), $code->uses );
```
Comment (dparker1005) [inline pmpro-sponsored-members.php:650]:
```suggestion
				$message = sprintf( _n( 'This code has %d use.', 'This code has %d uses.', $code->uses, 'pmpro-sponsored-members' ), $code->uses ), $code->uses );
```

**Review by dparker1005 — APPROVED** [review]
